global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Hand Gesture Recognition API
  - job_name: 'gesture-api'
    static_configs:
      - targets: ['gesture-api:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093